api_platform:
    title: You-Pim API
    version: 1.0.0
    enable_swagger_ui: true
    enable_re_doc: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 1000
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
        - '%kernel.project_dir%/src/ApiResource'
