<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251203162248 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE collection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE collection_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, label VARCHAR(255) NOT NULL, collection_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_28C3D9EE514956FD ON collection_translation (collection_id)');
        $this->addSql('ALTER TABLE collection_translation ADD CONSTRAINT FK_28C3D9EE514956FD FOREIGN KEY (collection_id) REFERENCES collection (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attribute_definition ALTER is_localizable SET DEFAULT false');
        $this->addSql('ALTER TABLE attribute_definition ALTER is_scopable SET DEFAULT false');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE collection_translation DROP CONSTRAINT FK_28C3D9EE514956FD');
        $this->addSql('DROP TABLE collection');
        $this->addSql('DROP TABLE collection_translation');
        $this->addSql('ALTER TABLE attribute_definition ALTER is_localizable DROP DEFAULT');
        $this->addSql('ALTER TABLE attribute_definition ALTER is_scopable DROP DEFAULT');
    }
}
