<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260522162257 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create asset, asset_flag and asset_asset_flag tables (Asset management phase 1)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE asset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, type VARCHAR(20) NOT NULL, mime_type VARCHAR(100) NOT NULL, filename VARCHAR(255) NOT NULL, size BIGINT NOT NULL, s3_key VARCHAR(512) DEFAULT NULL, s3_bucket VARCHAR(100) DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, duration INT DEFAULT NULL, checksum VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2AF5A5C77153098 ON asset (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2AF5A5C3C4A71D5 ON asset (s3_key)');
        $this->addSql('CREATE TABLE asset_flag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, color VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_35902E5277153098 ON asset_flag (code)');
        $this->addSql('CREATE TABLE asset_asset_flag (asset_id INT NOT NULL, asset_flag_id INT NOT NULL, PRIMARY KEY (asset_id, asset_flag_id))');
        $this->addSql('CREATE INDEX IDX_F371CD085DA1941 ON asset_asset_flag (asset_id)');
        $this->addSql('CREATE INDEX IDX_F371CD08F271A5B3 ON asset_asset_flag (asset_flag_id)');
        $this->addSql('ALTER TABLE asset_asset_flag ADD CONSTRAINT FK_F371CD085DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE asset_asset_flag ADD CONSTRAINT FK_F371CD08F271A5B3 FOREIGN KEY (asset_flag_id) REFERENCES asset_flag (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE asset_asset_flag DROP CONSTRAINT FK_F371CD085DA1941');
        $this->addSql('ALTER TABLE asset_asset_flag DROP CONSTRAINT FK_F371CD08F271A5B3');
        $this->addSql('DROP TABLE asset_asset_flag');
        $this->addSql('DROP TABLE asset');
        $this->addSql('DROP TABLE asset_flag');
    }
}
