<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251202145939 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sku_root VARCHAR(100) NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D34A04AD1850B32A ON product (sku_root)');
        $this->addSql('CREATE TABLE product_attribute_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(5) DEFAULT NULL, market VARCHAR(255) DEFAULT NULL, value TEXT DEFAULT NULL, values JSON DEFAULT NULL, product_id INT DEFAULT NULL, variant_id INT DEFAULT NULL, attribute_definition_id INT NOT NULL, option_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CCC4BE1F4584665A ON product_attribute_value (product_id)');
        $this->addSql('CREATE INDEX IDX_CCC4BE1F3B69A9AF ON product_attribute_value (variant_id)');
        $this->addSql('CREATE INDEX IDX_CCC4BE1F7492F274 ON product_attribute_value (attribute_definition_id)');
        $this->addSql('CREATE INDEX IDX_CCC4BE1FA7C41D6F ON product_attribute_value (option_id)');
        $this->addSql('CREATE TABLE product_variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sku VARCHAR(100) NOT NULL, ean VARCHAR(50) DEFAULT NULL, is_default BOOLEAN NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_209AA41D4584665A ON product_variant (product_id)');
        $this->addSql('ALTER TABLE product_attribute_value ADD CONSTRAINT FK_CCC4BE1F4584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_attribute_value ADD CONSTRAINT FK_CCC4BE1F3B69A9AF FOREIGN KEY (variant_id) REFERENCES product_variant (id)');
        $this->addSql('ALTER TABLE product_attribute_value ADD CONSTRAINT FK_CCC4BE1F7492F274 FOREIGN KEY (attribute_definition_id) REFERENCES attribute_definition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_attribute_value ADD CONSTRAINT FK_CCC4BE1FA7C41D6F FOREIGN KEY (option_id) REFERENCES attribute_option (id)');
        $this->addSql('ALTER TABLE product_variant ADD CONSTRAINT FK_209AA41D4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product_attribute_value DROP CONSTRAINT FK_CCC4BE1F4584665A');
        $this->addSql('ALTER TABLE product_attribute_value DROP CONSTRAINT FK_CCC4BE1F3B69A9AF');
        $this->addSql('ALTER TABLE product_attribute_value DROP CONSTRAINT FK_CCC4BE1F7492F274');
        $this->addSql('ALTER TABLE product_attribute_value DROP CONSTRAINT FK_CCC4BE1FA7C41D6F');
        $this->addSql('ALTER TABLE product_variant DROP CONSTRAINT FK_209AA41D4584665A');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_attribute_value');
        $this->addSql('DROP TABLE product_variant');
    }
}
