<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251202092347 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attribute_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, sort_order INT NOT NULL, attribute_definition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_78672EEA7492F274 ON attribute_option (attribute_definition_id)');
        $this->addSql('CREATE TABLE attribute_option_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, label VARCHAR(255) NOT NULL, option_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E4DCC60DA7C41D6F ON attribute_option_translation (option_id)');
        $this->addSql('ALTER TABLE attribute_option ADD CONSTRAINT FK_78672EEA7492F274 FOREIGN KEY (attribute_definition_id) REFERENCES attribute_definition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attribute_option_translation ADD CONSTRAINT FK_E4DCC60DA7C41D6F FOREIGN KEY (option_id) REFERENCES attribute_option (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attribute_option DROP CONSTRAINT FK_78672EEA7492F274');
        $this->addSql('ALTER TABLE attribute_option_translation DROP CONSTRAINT FK_E4DCC60DA7C41D6F');
        $this->addSql('DROP TABLE attribute_option');
        $this->addSql('DROP TABLE attribute_option_translation');
    }
}
