<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260521121534 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE taxonomy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FD12B83D77153098 ON taxonomy (code)');
        $this->addSql('CREATE INDEX IDX_FD12B83D727ACA70 ON taxonomy (parent_id)');
        $this->addSql('CREATE TABLE taxonomy_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, label VARCHAR(255) NOT NULL, taxonomy_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C1F82AA59557E6F6 ON taxonomy_translation (taxonomy_id)');
        $this->addSql('ALTER TABLE taxonomy ADD CONSTRAINT FK_FD12B83D727ACA70 FOREIGN KEY (parent_id) REFERENCES taxonomy (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE taxonomy_translation ADD CONSTRAINT FK_C1F82AA59557E6F6 FOREIGN KEY (taxonomy_id) REFERENCES taxonomy (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE taxonomy DROP CONSTRAINT FK_FD12B83D727ACA70');
        $this->addSql('ALTER TABLE taxonomy_translation DROP CONSTRAINT FK_C1F82AA59557E6F6');
        $this->addSql('DROP TABLE taxonomy');
        $this->addSql('DROP TABLE taxonomy_translation');
    }
}
