<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260521132309 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create parameter table and seed system defaults (TAXONOMY_LEVEL_MAX)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE parameter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, value TEXT NOT NULL, type VARCHAR(20) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2A97911077153098 ON parameter (code)');

        $this->addSql("INSERT INTO parameter (code, value, type, description) VALUES ('TAXONOMY_LEVEL_MAX', '5', 'integer', 'Maximum nesting depth allowed for the taxonomy tree (root counts as level 1).')");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE parameter');
    }
}
