<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260527_AssetTransformation extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create asset_transformation and transformation_step tables (Phase 1 — Domain & Versioning Foundation).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE asset_transformation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(150) NOT NULL, version_hash VARCHAR(40) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C8C43E9277153098 ON asset_transformation (code)');
        $this->addSql('CREATE TABLE transformation_step (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, params JSON DEFAULT NULL, position INT DEFAULT 0 NOT NULL, transformation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B86EAF7F14FD34D2 ON transformation_step (transformation_id)');
        $this->addSql('ALTER TABLE transformation_step ADD CONSTRAINT FK_B86EAF7F14FD34D2 FOREIGN KEY (transformation_id) REFERENCES asset_transformation (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE transformation_step DROP CONSTRAINT FK_B86EAF7F14FD34D2');
        $this->addSql('DROP TABLE transformation_step');
        $this->addSql('DROP TABLE asset_transformation');
    }
}
