<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251202081437 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attribute_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, type VARCHAR(50) NOT NULL, is_localizable BOOLEAN NOT NULL, is_scopable BOOLEAN NOT NULL, validation_rules JSON DEFAULT NULL, allowed_values JSON DEFAULT NULL, unit VARCHAR(50) DEFAULT NULL, is_required BOOLEAN NOT NULL, default_value VARCHAR(255) DEFAULT NULL, help_text TEXT DEFAULT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6C5628BD77153098 ON attribute_definition (code)');
        $this->addSql('DROP TABLE test');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE test (id INT NOT NULL, test VARCHAR DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('DROP TABLE attribute_definition');
    }
}
